### PR TITLE
Super basic dockerfile

### PR DESCRIPTION
**Pull request by natemcintosh**
Based on uv's [docker integration](https://docs.astral.sh/uv/guides/integration/docker/) docs. 

This is the simplest version that they suggest.

### CODE REVIEW

**Comment by natemcintosh** [comment]
Next steps here could be to add an action that automatically builds this dockerfile. Could do that in this PR, or another; don't think it matters too much.

**Review by amondal2 — APPROVED** [review]
Looks good. We can handle building the container once we have some code to build imo. 

As a related note, we should make sure that once our actions start interacting with Azure, we 1) configure the credentials as secrets in the repo and 2) make sure we use the CFA self-hosted runners

**Comment by natemcintosh** [comment]
Yea, that would be really great. For the CFA self-hosted runners, do we need to use those for everything? Or just the stuff that interacts with Azure?

**Comment by amondal2** [comment]
I think just for the stuff that interacts with Azure as they are within the EXT subnet. The GH-provided ones should be fine for the other actions (test, pre-commit, etc)

**Pull request merged**
